In [ ]:
import numpy as np

In [24]:
#1.a.i
JMT = [10, 13, 20]
UIA = [21, 9, 1]
Name = [JMT, UIA]

#1.a.ii
ID = [[2, 0, 3], [1, 2, 8]]

m_A = np.array(Name)
m_B = np.array(ID)

print("Matrix A: \n", m_A) 
print("Matrix B: \n", m_B)

Matrix A: 
 [[10 13 20]
 [21  9  1]]
Matrix B: 
 [[2 0 3]
 [1 2 8]]


In [25]:
#2. Matrix Addition 

M_A = np.array(m_A)
M_B = np.array(m_B)

M_C = M_A + M_B

print("Matrix C: \n",  M_C)

Matrix C: 
 [[12 13 23]
 [22 11  9]]


In [27]:
#3. Scalar Multiplication

M_A = np.array(m_A)

scalar = 2

M_D = np.multiply(M_A, scalar)

print("Matrix D: \n", M_D)

Matrix D: 
 [[20 26 40]
 [42 18  2]]


In [29]:
#4. Matrix Transpose

M_B = np.array(m_B)

M_E = np.transpose(M_B)

print("Matrix E: \n", M_E)

Matrix E: 
 [[2 1]
 [0 2]
 [3 8]]


In [50]:
#5.Multiplication Matrix (a)

M_C = (M_A + M_B)
M_E = np.transpose(M_B)

M_F = np.matmul(M_C, M_E)

print("Matrix F(a): \n", M_F)

Matrix F(a): 
 [[ 93 222]
 [ 71 116]]


In [44]:
#5 Multiplication Matrix (b)

M_C = (M_A + M_B)
M_E = np.transpose(M_B)

M_F = [[0,0],
       [0,0]]

M_F = np.dot(M_C, M_E)

print("Matrix F(b): \n", M_F)

Matrix F(b): 
 [[ 93 222]
 [ 71 116]]


In [48]:
#6. Sum of all Elements

M_C = (M_A + M_B)

sum_C = np.sum(M_C)

print("Sum of Matrix C: \n", sum_C)

Sum of Matrix C: 
 90


In [49]:
#7. Zero Matrix

M_G = np.matrix(np.zeros((3,3)))

print("Matrix G: \n", M_G)

Matrix G: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
